### ISSUE TITLE
dosemu-setupfreedos Python helper script gets the wrong directory when used with "-v full"

### ISSUE THREAD

**Issue by uralets** [dosemu2/install-freedos#12]
Line 105:
cmddir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'share', 'dosemu', 'commands', 'c')
Whereas it should be:
cmddir = os.path.join(os.path.dirname(os.path.abspath(__file__)), **'..', '..',** 'share', 'dosemu', 'commands', 'c')

Otherwise it gets the wrong directory to look for **fdconfig.sys**

The script gets installed into /usr/libexec/dosemu/dosemu-setupfreedos, while fdconfig.sys is in /usr/share/dosemu/dosemu2-cmds-0.3/c/fdconfig.sys - that's **TWO** '..' (directories) above /usr/libexec/dosemu/, not one.

As installed from the PPA package.

See the details in https://github.com/dosemu2/dosemu2/issues/1599

**Comment by stsp** [comment]
Could you please check if it now works?

**Comment by uralets** [comment]
> Could you please check if it now works?
> 

I see the package has been updated in the PPA. I'm using it.
I need to re-download the FreeDOS files.
dosemu-setupfreedos won't do it automagically for me so I launch
dosemu-downloaddos directly. If started without arguments, it just
silently aborts (even tho all the args are "optional").
Trying /usr/libexec/dosemu/dosemu-downloaddos -o freedos12 gives:
<successfully downloads a bunch of files>
Downloading 
https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/base/command.zip
...
Traceback (most recent call last):
  File "/usr/libexec/dosemu/dosemu-downloaddos", line 205, in <module>
    download_dos(dos_to_download, destination)
  File "/usr/libexec/dosemu/dosemu-downloaddos", line 170, in
download_dos
    download_FREEDOS_FULL_ARCHIVES(FREEDOS12_URL, destination)
  File "/usr/libexec/dosemu/dosemu-downloaddos", line 117, in
download_FREEDOS_FULL_ARCHIVES
    download_file(freedos_url + '/repos/base/' + filename + '.zip',
destination)
  File "/usr/libexec/dosemu/dosemu-downloaddos", line 57, in
download_file
    with urllib.request.urlopen(urllib.parse.quote_plus(source, "\./_-
:")) as response, open(destination_file, 'wb') as f:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in
http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in
http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by stsp** [comment]
Well if you read the doc I mentioned
yesterday, you'll see that you need to
do `dosemu-install3rdpartydos` from another
package and then `dosemu -dos svardos`
to run freedos.

I don't know why do we still have the
raw "freedos12" option in a scripts,
and to save ppl like you from errors,
I should probably delete it.

**Comment by uralets** [comment]
I have yet to read all your replies (haven't opened the ones
considering the docs yet) - sorry.
But I can't but notice that situations like this kinda reinforce my
point re documentation..

**Comment by stsp** [comment]
How does it re-enforce it, if the
documentation is there but you
didn't open it yet?
Its still here:
https://github.com/dosemu2/dosemu2/wiki/installing-various-DOSes

But I admit that people like to look
into sources rather than docs, and
the findings like this are important
as well. If this "freedos12" option is
a remnant then it should either be
restored or deleted, so thanks for
finding that artefact.
@jschwartzenberg do you have any
suggestions about the (undocumented)
"freedos12" option?

**Comment by uralets** [comment]
also the whole purpose of me even turning to these helper scripts was
to check if running with the vanilla FreeDOS instead of fdpp kernel
would make the game I'm interested in run better (I've just figured
from the script names that they're supposed to somehow help me setup
FreeDOS - and I'm still not sure if it is so lol). Even though I
doubted that from the start (that turning from fdpp to a FreeDOS would
help me), you can see I've run into a host of various other issues.
With fdpp DOSEMU2 just magically works out of the box, without it - not
so much, to put it mildly...
If there's no point in trying to install FreeDOS instead of running
with fdpp - I'm not even that interested tbh.

**Comment by stsp** [comment]
I am pretty sure if the game is
slow or GM music doesn't work -
there is no reason at all to switch
DOS.
And if the problem is in too much
CPU usage, then there is no need
to run that game under dosemu2
yet. :) Power management will be
worked out, but not now.

> (I've just figured
> from the script names that they're supposed to somehow help me setup
> FreeDOS

These scripts are installed into
share or libexec dirs. Running them
directly was obviously an ask for
troubles. There is another package,
install-otherdos, to help you install
freedos & co.

**Comment by uralets** [comment]
В Ср, 09/03/2022 в 07:50 -0800, Stas Sergeev пишет:
> How does it re-enforce it, if the
> documentation is there but you
> didn't open it yet?
> Its still here:
> https://github.com/dosemu2/dosemu2/wiki/installing-various-DOSes
> 
> 
I admit I totally forgot that github repos have wikis - not many
projects put anything there at all. And there's no indication on the
main page that there is something there after all.

I'll still say that the docs that are there now might benefit from at
least making their location more visible. Like, well, the main github
page?

**Comment by uralets** [comment]
В Ср, 09/03/2022 в 07:57 -0800, Stas Sergeev пишет:
> I am pretty sure if the game is
> slow or GM music doesn't work -
> there is no reason at all to switch
> DOS.
Guess so.

> And if the problem is in too much
> CPU usage, then there is no need
> to run that game under dosemu2
> yet. :) Power management will be
> worked out, but not now.
> 
it's not about PM at all - not that my PC is running hot or something.
It's about my expectation that the game would use less host resources
than in DOSBOX, while it uses even more AND runs worse for that. This
is my actual core complaint - everything else I've reported is
circumstantial at best (besides MIDI setup probably)
> 
These scripts are installed into
share or libexec dirs.
Have no doubt, I've noticed that...

> Running them
> directly was obviously an ask for
> troubles.
These scripts just were the most visible stuff.


> There is another package,
> install-otherdos, to help you install
> freedos & co.
> 
I see now.

**Comment by stsp** [comment]
> It's about my expectation that the game would use less host resources
> than in DOSBOX, while it uses even more AND runs worse for that.

Both parts are identified: it runs
worse because of scaling. Try
disabling filters and see if that
helps.

I admit improving wiki/making it
more visible is a good task. If you
can help with that, you can check
out the gh-pages branch, edit the
html files and make a PR, helping
the prohect. :)
