### ISSUE TITLE
Add test downloads function

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/install-freedos#18]
As mentioned here in the early part of this PR https://github.com/dosemu2/dosemu2/pull/1702 Github actions is bandwidth limited. I'd like to be able to test install_freedos to be sure that the urls are current, but without actually doing the download. Do you think it would be possible to add a test option to the program?

**Comment by stsp** [comment]
I think that would be very
good, and eg 1 package to
still download, like mem,
and test that mem works
as expected.

**Comment by stsp** [comment]
@jschwartzenberg ? :)

**Comment by jschwartzenberg** [comment]
> eg 1 package

Sadly that would not have caught the issue we had recently because it was just a single package that had a name change that broke 1.2. (`command.zip` became `freecom.zip`)

**Comment by andrewbird** [comment]
I was hoping that each of the packages would be tried in the fashion you mentioned here https://github.com/dosemu2/dosemu2/pull/1702#issuecomment-1163631182 for the reason @jschwartzenberg just mentioned :-)

**Comment by stsp** [comment]
Yes, I mean exactly that.
- Try each package
- D/L one and do some real testing

**Comment by stsp** [comment]
So no one wants to code in python here? :)
