### ISSUE TITLE
Struggling to install userspace tools

### ISSUE THREAD

**Issue by haenschen** [dosemu2/install-freedos#19]
On a fresh Ubuntu 22.04 I am struggling to install the userspace tools although I remember I recently was able to do it.
I am compiling dosemu2 pre9 from source and making use of comcom32 and fdpp-dev. Then I start dosemu once. After that I install the scripts
`sudo apt-get install install-freedos`
succeeds
`0.1-2~202207251944~ubuntu22.04.1`
dosemu then offers me to install userspace tools via `insfdusr`
which fails with
```
unix: /usr/local/libexec/dosemu/dosemu-installfreedosuserspace not found
freedos installation failed.
```
Obviously the requested directory doesn't exist on my system. What am I doing wrong?

**Comment by haenschen** [comment]
In 
`/usr/libexec/dosemu`
I found the three files
```
dosemu-downloaddos
dosemu-installfreedosuserspace
dosemu-setupfreedos
```
Mind the missing "local" in the path

Creating the right directory and copying the files enables me to do insfdusr in dosemu.

**Comment by stsp** [comment]
Use `--libexecdir=/usr/libexec` configure
option when building by hands.
